{% set name = "python-slugify" %}
{% set version = "6.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba72aa9d9f0514c0c3dd4430442f698ccc27a24d19630473663a71e3ec606bc1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - slugify=slugify.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - text-unidecode >=1.3
    - unidecode >=1.1.1

test:
  requires:
    - pip
  imports:
    - slugify
  source_files:
    - test.py
  commands:
    - python -m pip check
    - slugify --help
    - python test.py

about:
  home: https://github.com/un33k/python-slugify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python Slugify application that handles Unicode
  dev_url: https://github.com/un33k/python-slugify

extra:
  recipe-maintainers:
    - proinsias
    - sodre
    - bollwyvl
