{% set name = "python-slugify" %}
{% set version = "4.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 69a517766e00c1268e5bbfc0d010a0a8508de0b18d30ad5a1ff357f8ae724270

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - slugify=slugify.__main__:main

requirements:
  host:
    - pip
    - python
  run:
    - python
    - text-unidecode >=1.3
    - unidecode >=1.1.1

test:
  requires:
    - pip
  imports:
    - slugify
  source_files:
    - test.py
  commands:
    - python -m pip check
    - slugify --help
    - python test.py

about:
  home: https://github.com/un33k/python-slugify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python Slugify application that handles Unicode
  dev_url: https://github.com/un33k/python-slugify

extra:
  recipe-maintainers:
    - proinsias
    - sodre
    - bollwyvl
