{% set name = "python-slugify" %}
{% set version = "5.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 744cd5d42b381687657f3b652d1d9b183c0870ec43de23be682b6d83d69c6962

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - slugify=slugify.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - text-unidecode >=1.3
    - unidecode >=1.1.1

test:
  requires:
    - pip
  imports:
    - slugify
  source_files:
    - test.py
  commands:
    - python -m pip check
    - slugify --help
    - python test.py

about:
  home: https://github.com/un33k/python-slugify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python Slugify application that handles Unicode
  dev_url: https://github.com/un33k/python-slugify

extra:
  recipe-maintainers:
    - proinsias
    - sodre
    - bollwyvl
