{% set version = "7.0.0" %}

package:
  name: python-slugify
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/p/python-slugify/python-slugify-{{ version }}.tar.gz
    sha256: 7a0f21a39fa6c1c4bf2e5984c9b9ae944483fd10b54804cb0e23a3ccd4954f0b
  - url: https://raw.githubusercontent.com/un33k/python-slugify/v{{ version }}/test.py
    sha256: 2cd6220bd1938284a40f70ceb6af6e46fa1d276c62f026dd7ce548780640871d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - slugify=slugify.__main__:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - text-unidecode >=1.3
    - unidecode >=1.1.1

test:
  requires:
    - pip
  imports:
    - slugify
  source_files:
    - test.py
  commands:
    - python -m pip check
    - slugify --help
    - python test.py

about:
  home: https://github.com/un33k/python-slugify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python Slugify application that handles Unicode
  dev_url: https://github.com/un33k/python-slugify

extra:
  recipe-maintainers:
    - proinsias
    - sodre
    - bollwyvl
