{% set pytest_args = "pytest test.py -vv --cov=slugify --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=92" %}
{% set version = "8.0.3" %}
{% set pytest_args = "pytest test.py -vv --cov=slugify --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=92" %}

package:
  name: python-slugify-split
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/p/python-slugify/python-slugify-{{ version }}.tar.gz
    sha256: e04cba5f1c562502a1175c84a8bc23890c54cdaf23fccaaf0bf78511508cabed
  - url: https://raw.githubusercontent.com/un33k/python-slugify/v{{ version }}/test.py
    sha256: 9920b8e59978fa1a3d3f4a6728a5b4e0bfcfa1804983a117170c2709a28dee6c

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
  run:
    - python >=3.7

test:
  commands:
    - exit 0

outputs:
  - name: python-slugify
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
      entry_points:
        - slugify=slugify.__main__:main
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - text-unidecode >=1.3
      run_constrained:
        # ships slugify in site-packages and bin
        - slugify <0
        # ships slugify in site-packages
        - awesome-slugify <0
        # optional, GPLed dep with pin, see `python-slugify-with-unidecode`
        - unidecode >=1.1.1
      test:
        requires:
          - pip
          - pytest-cov
        imports:
          - slugify
        source_files:
          - test.py
        commands:
          - pip check
          - slugify --help
          - {{ pytest_args }}

  - name: python-slugify-with-unidecode
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - {{ pin_subpackage("python-slugify", max_pin="x.x.x") }}
        - python >=3.7
        - unidecode
    test:
      requires:
        - pip
        - pytest-cov
      imports:
        - slugify
      source_files:
        - test.py
      commands:
        - pip check
        - slugify --help
        - {{ pytest_args }}

about:
  home: https://github.com/un33k/python-slugify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python Slugify application that handles Unicode
  dev_url: https://github.com/un33k/python-slugify

extra:
  feedstock-name: python-slugify
  recipe-maintainers:
    - proinsias
    - sodre
    - bollwyvl
