{% set name = "python-slugify" %}
{% set version = "3.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 575d03256a132fc1efb4c52966c6eb11c57a13b071618f0b26076057a23f6937
  patches:
      - fix_command.patch

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - slugify = slugify.cli:main

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - text-unidecode 1.2
    - unidecode >=0.04.16

test:
  imports:
    - slugify

  source_files:
    - test.py

  commands:
    - slugify --help
    - python test.py


about:
  home: https://github.com/un33k/python-slugify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python Slugify application that handles Unicode'
  dev_url: https://github.com/un33k/python-slugify

extra:
  recipe-maintainers:
    - proinsias
    - sodre
