{% set name = "python-slugify" %}
{% set version = "1.2.5" %}
{% set sha256 = "5dbb360b882b2dabe0471a1a92f604504d83c2a73c71f2098d004ab62e695534" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
      - fix_command.patch

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - slugify = slugify.cli:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - unidecode >=0.04.16

test:
  imports:
    - slugify

  commands:
    - slugify --help


about:
  home: https://github.com/un33k/python-slugify
  license: MIT
  license_family: MIT
  # license_file: LICENSE There is no license in python-slugify
  summary: 'A Python Slugify application that handles Unicode'
  dev_url: https://github.com/un33k/python-slugify

extra:
  recipe-maintainers:
    - proinsias
    - sodre
