{% set version = "8.0.4" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

{% set pytest_args = "pytest test.py -vv --cov=slugify --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=92" %}

package:
  name: python-slugify
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/p/python-slugify/python-slugify-{{ version }}.tar.gz
    sha256: 59202371d1d05b54a9e7720c5e038f928f45daaffe41dd10822f3907b937c856
  - url: https://raw.githubusercontent.com/un33k/python-slugify/v{{ version }}/test.py
    sha256: 96a2fb00cb9a225c473cd0bcfab01286f16d47b51368a986a250e00a50ddcc92

build:
  number: 1
  noarch: python
  script: 
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check
  entry_points:
    - slugify = slugify.__main__:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - text-unidecode >=1.3
  run_constrained:
    # ships slugify in site-packages and bin
    - slugify <0
    # ships slugify in site-packages
    - awesome-slugify <0
    # optional, GPLed dep with pin, see `python-slugify-with-unidecode`
    - unidecode >=1.1.1

test:
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}
  imports:
    - slugify
  source_files:
    - test.py
  commands:
    - pip check
    - slugify --help
    - {{ pytest_args }}

outputs:
  - name: python-slugify

  - name: python-slugify-with-unidecode
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("python-slugify", max_pin="x.x.x") }}
        - unidecode
    test:
      requires:
        - pip
        - pytest-cov
      imports:
        - slugify
      source_files:
        - test.py
      commands:
        - pip check
        - slugify --help
        - {{ pytest_args }}

about:
  home: https://github.com/un33k/python-slugify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python Slugify application that handles Unicode
  dev_url: https://github.com/un33k/python-slugify

extra:
  feedstock-name: python-slugify
  recipe-maintainers:
    - proinsias
    - sodre
    - bollwyvl
