travis:
  secure:
    BINSTAR_TOKEN: EjTLnXhYbFLX03+h5cqRspC+Deu2UMXqLyu4bLEAhbFdueS8DUlnrgQP3/94FGxah643HKGH3GFe/U4lKdOs8ULOZM9PfezRfkqS5+Bz2r7Aip79o37/foO/Pl9OxyNlnvKzDH8gWmFZsOOiuE4so+ibGqQLTR+IRDTdkIht6UnlwUoaSiIDMKUayM6/BpQLXBLkXqoV/Fm3J2NbVC0QnPoEH95BiUFZ5VHzfuBWw41SiGi6Y0jOo857CqwQav1mQwffEgCAV1YQzxobopDjg6vy4J0WdMD74nx35X1pP0ASOk+RfABihfiMtUCxpeeWGqtagcp/9PDsvDy9vmScGUDtpyMGxam+FgRdBXgTVcLNFVyNCS6+tfcj5ru4wcDQmvByZnWMZEpJi0OIug4wIB8p0vQy3V69zAbLIjAgmBPPv1un8okPUQ1Vr2QKEng8mE1VLox5ocjk02y4TV+YJ0n8FJXhvD8brCINIx31+UoM24Jy5VWCrW8PZVtw/LMC16/6pYjjK9LwooW0jMvPJBrcpXm7je4E8gEP37Ck17aRqOFZ2iUMj8bioJH4WST+GzUie0VTJb8cKMInlDkDcKCUI9iLNPrGo/uDZR5EwF4re4wzyuaW2yFAkwBtzq+/46hSntoJmryZeaYvT16VWNAn5+KKNepo/bdCT5OeDk0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
